# Generated by Django 3.1.2 on 2020-10-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201013_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.FileField(blank=True, default='test.mp3', null=True, upload_to='')),
            ],
        ),
    ]
